FROM python:3.11.9-slim-bullseye
RUN apt update
RUN apt-get -y install gcc

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN poetry install --without dev