FROM python:3.11.9-slim-bullseye

WORKDIR /app

RUN pip install poetry
COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN poetry install --with dev

EXPOSE 8888
ENTRYPOINT ["poetry", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]