random_state: 0

tf_idf:
    max_features: 1500
    stop_words: "english"

logistic_regression:
    max_iter: 1000
    penalty: "l2"

random_forest:
    n_estimators: 60
    max_depth: 12
    n_jobs: 10