name: Run dvc pipeline

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  dvc-pipeline-running:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --without dev
      - name: Run pipeline
        run: |
          poetry run dvc repro